name: 发布到 Test PyPI

# 发布了新版本时，无论是否为预发行版本
on:
  release:
    types: [published]

permissions: {}

jobs:
  build:
    name: 构建
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: 签出仓库
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: 设置 Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.14"

      - name: 安装 uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          enable-cache: false

      - name: 构建
        shell: bash
        run: uv build --no-sources

      # 你可以在这里添加一些测试，以验证构建出来的东西可以用。

      - name: 上传分发文件为工件
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: dist
          path: dist/

  publish:
    name: 发布
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: testpypi
    permissions:
      id-token: write # https://docs.astral.sh/uv/guides/integration/github/#publishing-to-pypi
    steps:
      - name: 安装 uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          enable-cache: false

      - name: 下载分发工件
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: dist
          path: dist/

      - name: 生成 PEP 740 attestations
        uses: astral-sh/attest-action@f589a42a7efb6fe400b4f400de60b4bc90390027 # v0.0.6

      - name: 发布
        shell: bash
        run: uv publish --publish-url "https://test.pypi.org/legacy/" --check-url "https://test.pypi.org/simple"
