name: Pytest

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  run-pytest:
    name: 运行 Pytest 测试
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          # 你的包支持的所有系统
          - macos-latest
          - ubuntu-latest
          - windows-latest
        python-version:
          # 你的包支持的所有 Python 版本
          - 3.10.x
          - 3.11.x
          - 3.12.x
          - 3.13.x
          - 3.14.x
    env:
      PYTHONIOENCODING: utf-8

    steps:
      - name: 检出代码
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: 配置 Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: 安装 uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          enable-cache: false

      - name: 安装依赖
        shell: bash
        run: uv sync

      - name: 运行测试
        shell: bash
        run: uv run pytest -vv
